// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkQyBqrfLsOxnUrm6KveyUKPFpzAj_shE',
    appId: '1:500622971898:web:226a1751e693e435884a43',
    messagingSenderId: '500622971898',
    projectId: 'flutterchat-7f358',
    authDomain: 'flutterchat-7f358.firebaseapp.com',
    storageBucket: 'flutterchat-7f358.appspot.com',
    measurementId: 'G-WD07BMML18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArj0RNY60XqdHMvNtjo8wIVX7ovPv9fx4',
    appId: '1:500622971898:android:330af9b377463318884a43',
    messagingSenderId: '500622971898',
    projectId: 'flutterchat-7f358',
    storageBucket: 'flutterchat-7f358.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApDaOGRIosGZVa_Fl38t9VXP8-WGNfkXQ',
    appId: '1:500622971898:ios:d2ad950d2b7369b4884a43',
    messagingSenderId: '500622971898',
    projectId: 'flutterchat-7f358',
    storageBucket: 'flutterchat-7f358.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApDaOGRIosGZVa_Fl38t9VXP8-WGNfkXQ',
    appId: '1:500622971898:ios:d2ad950d2b7369b4884a43',
    messagingSenderId: '500622971898',
    projectId: 'flutterchat-7f358',
    storageBucket: 'flutterchat-7f358.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );
}
